#!/bin/sh
#
# puppet-clean-host         Script to clean this hostname from puppet for reuse
#
# chkconfig: 345 50 50
# description: Ensure that puppet contains no records for our hostname

DOM=\`facter domain\`

# strip off any leading "aws." from the domain name and then append to the end of the puppet master hostname
DOM=\${DOM#aws\.}
DOM=\${DOM:-brislabs.com}
PUPPET_SERVER="puppetaws.\${DOM}"

ssh -o StrictHostKeyChecking=no -i /opt/puppet-clean/.ssh/janitor_rsa janitor@\${PUPPET_SERVER} \`facter fqdn\`
